spring:
  main:
    banner-mode: off
  application:
    name: reactive-study

  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/pet-db

server:
  forward-headers-strategy: framework

logging:
  level:
    com:
      study:
        webflux: DEBUG
  file:
    path: logs