spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: root
      authentication-database: admin
      database: pet-db
  application:
    name: reactive-study
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null
logging:
  level:
    com:
      study:
        webflux: INFO