spring:
  main:
    banner-mode: off
  application:
    name: reactive-study

  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: ${SPRING_JACKSON_DESERIALIZATION_FAIL_ON_UNKNOWN_PROPERTIES}
    serialization:
      write-dates-as-timestamps: ${SPRING_JACKSON_SERIALIZATION_WRITE_DATE_AS_TIMESTAMPS}
    default-property-inclusion: ${SPRING_JACKSON_DEFAULT_PROPERTY_INCLUSION}

  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST}
      port: ${SPRING_DATA_MONGODB_PORT}
      username: ${SPRING_DATA_MONGODB_USERNAME}
      password: ${SPRING_DATA_MONGODB_PASSWORD}
      authentication-database: ${SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE}
      database: ${SPRING_DATA_MONGODB_DATABASE}

server:
  forward-headers-strategy: ${SERVER_FORWARD_HEADERS_STRATEGY}

logging:
  level:
    com:
      study:
        webflux: ${LOGGING_LEVEL_COM_STUDY_WEBFLUX}
  file:
    path: ${LOGGING_FILE_PATH}