spring:
  main:
    banner-mode: off
  application:
    name: reactive-study

  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: ${SPRING_JACKSON_DESERIALIZATION_FAIL_ON_UNKNOWN_PROPERTIES}
    serialization:
      write-dates-as-timestamps: ${SPRING_JACKSON_SERIALIZATION_WRITE_DATES_AS_TIMESTAMPS}
    default-property-inclusion: ${SPRING_JACKSON_DEFAULT_PROPERTY_INCLUSION}

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

server:
  forward-headers-strategy: ${SERVER_FORWARD_HEADERS_STRATEGY}

logging:
  level:
    com:
      study:
        webflux: ${LOGGING_LEVEL_COM_STUDY_WEBFLUX}
  file:
    path: ${LOGGING_FILE_PATH}