application:
  type: application
  environment: dev
  tier: backend
  ingress:
    controller: nginx
  service:
    port: 80
  pod:
    replicas: 1
    container:
      port: 8080
      protocol: TCP

spring:
  data:
    mongodb:
      host: reactive-mongodb-cluste.o3q83.mongodb.net
      port: 27017
      username: admin
      password: admin
      authenticationDatabase: admin
      database: pet-db

server:
  forwardHeadersStrategy: framework
logging:
  level:
    com:
      study:
        webflux: DEBUG
