# kubernetes
application:
  type: application
  environment: dev
  tier: backend
  ingress:
    controller: nginx
  service:
    port: 80
  pod:
    replicas: 1
    container:
      port: 8080
      protocol: TCP

# application.yaml
spring:
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    serialization:
      writeDatesAsTimestamps: false
    defaultPropertyInclusion: non_null

  data:
    mongodb:
      uri: mongodb+srv://admin:admin@reactive-mongodb-cluste.o3q83.mongodb.net/pet-db

server:
  forwardHeadersStrategy: framework

logging:
  level:
    com:
      study:
        webflux: DEBUG
