apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}
  labels:
    {{- include "chart.labels" . | indent 4 }}
    {{- include "common.labels" . | indent 4 }}
data:
  logging.level.com.study.webflux: {{ .Values.logging.level.com.study.webflux }}
  logging.file.path: /opt/{{ .Release.Name }}/logs
  server.forward-headers-strategy: {{ .Values.server.forwardHeadersStrategy }}
  spring.data.mongodb.host: {{ .Values.spring.data.mongodb.host }}
  spring.data.mongodb.port: {{ .Values.spring.data.mongodb.port | quote }}
  spring.data.mongodb.username: {{ .Values.spring.data.mongodb.username }}
  spring.data.mongodb.password: {{ .Values.spring.data.mongodb.password }}
  spring.data.mongodb.authentication-database: {{ .Values.spring.data.mongodb.authenticationDatabase }}
  spring.data.mongodb.database: {{ .Values.spring.data.mongodb.database }}
