apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}
  labels:
    {{- include "chart.labels" . | indent 4 }}
    {{- include "common.labels" . | indent 4 }}
data:
  logging.level.com.study.webflux: {{ .Values.logging.level.com.study.webflux }}
  logging.file.path: /opt/{{ .Release.Name }}/logs
  server.forward-headers-strategy: {{ .Values.server.forwardHeadersStrategy }}